== Feature Flags

The following system properties are available for toggling or specifying particular features to turn on or off.
Like any system properties, they should be considered experimental and subject to removal without notice.

* `com.cloudbees.plugins.credentials.UseOwnPermission` - Enables the Credentials/UseOwn permission type which allows a
user to provide their own user-scoped credentials to a build. When this feature flag is not specified, this permission
is ignored in favor of Job/Build. When the flag is enabled, Credentials/UseOwn is only implied by Overall/Administer by
default.

* `com.cloudbees.plugins.credentials.UseItemPermission` - Enables the Credentials/UseItem permission type which allows a
user to select and use the credentials that the job or item has access to. This permission is implied by
Job/Configure, and when the feature flag is not present, then the permission is ignored in favor of Job/Configure.

* `com.cloudbees.plugins.credentials.CredentialsProvider.fingerprintEnabled` - Overrides the default behavior that
credentials tracking is handled by Jenkins fingerprints. This feature flag is enabled by default and can be disabled
by setting the property to `false`.
